# Generated by Django 3.0.8 on 2020-07-03 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=15, verbose_name='班级名称')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('portrait', models.ImageField(default='/media/portraits/no_portrait.png', upload_to='portraits', verbose_name='头像')),
                ('user_type', models.CharField(choices=[('TC', 'Teacher'), ('ST', 'Student')], default='ST', max_length=10)),
                ('school', models.CharField(blank=True, max_length=15, null=True, verbose_name='所在院校')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='电子邮件')),
                ('belong_to_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_to_class', to='account.Class', verbose_name='所在院校')),
            ],
        ),
    ]
