# Generated by Django 3.0.8 on 2020-07-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='null', max_length=20, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='portrait',
            field=models.ImageField(default='portraits/no_portrait.png', upload_to='portraits', verbose_name='头像'),
        ),
    ]
