# Generated by Django 3.0.8 on 2020-07-06 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200705_1053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-user_type']},
        ),
    ]
