# Generated by Django 3.0.8 on 2020-07-04 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_auto_20200704_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default='null', max_length=20, verbose_name='课程名称')),
                ('credit', models.DecimalField(decimal_places=1, default=0.0, max_digits=2, verbose_name='学分')),
                ('length', models.SmallIntegerField(default=0, verbose_name='学时')),
                ('include_class', models.CharField(default='', max_length=50, verbose_name='所含班级')),
                ('status', models.SmallIntegerField(choices=[('IN', 1), ('OUT', 0)], default='OUT', verbose_name='课堂状态')),
                ('pub_time', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(default='章老师', on_delete=django.db.models.deletion.PROTECT, related_name='user_create_course', to='account.User', verbose_name='创建老师')),
                ('students', models.ManyToManyField(blank=True, null=True, related_name='courses', to='account.User')),
            ],
            options={
                'ordering': ['-status'],
            },
        ),
    ]
