# Generated by Django 3.0.8 on 2020-07-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '正在上课'), (0, '未上课')], default=0, verbose_name='课堂状态'),
        ),
    ]
