# Generated by Django 3.0.8 on 2020-07-04 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200704_0931'),
        ('api', '0002_auto_20200704_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(default='abc123', max_length=6, verbose_name='课程暗号'),
        ),
        migrations.AlterField(
            model_name='course',
            name='creator',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.PROTECT, related_name='user_create_course', to='account.User', verbose_name='创建老师'),
        ),
        migrations.AlterField(
            model_name='course',
            name='pub_time',
            field=models.DateTimeField(auto_now=True, verbose_name='发布时间'),
        ),
        migrations.CreateModel(
            name='PPT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppt_name', models.CharField(max_length=20, verbose_name='课件名称')),
                ('file', models.FileField(default='/ppts/no_ppt.ppt', upload_to='ppts', verbose_name='课件文件')),
                ('pub_time', models.DateTimeField(auto_now=True, verbose_name='上传时间')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_upload_ppt', to='account.User', verbose_name='上传者')),
            ],
            options={
                'ordering': ['pub_time'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', verbose_name='试题内容')),
                ('exercise_type', models.SmallIntegerField(choices=[(1, '选择题'), (0, '简答题')], default=0, verbose_name='试题类型')),
                ('pub_time', models.DateTimeField(auto_now=True, verbose_name='上传时间')),
                ('upload_file', models.FileField(blank=True, null=True, upload_to='exercise', verbose_name='试题文件')),
                ('choice_num', models.SmallIntegerField(default=0, verbose_name='选项个数')),
                ('choice_A', models.CharField(default='', max_length=50, verbose_name='选项A')),
                ('choice_B', models.CharField(default='', max_length=50, verbose_name='选项B')),
                ('choice_C', models.CharField(default='', max_length=50, verbose_name='选项C')),
                ('choice_D', models.CharField(default='', max_length=50, verbose_name='选项D')),
                ('correct_ans', models.SmallIntegerField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D')], default=0, verbose_name='正确选项')),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_upload_exercise', to='account.User', verbose_name='上传者')),
            ],
            options={
                'ordering': ['pub_time'],
            },
        ),
    ]
