# Generated by Django 3.0.8 on 2020-07-04 03:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200704_0931'),
        ('api', '0003_auto_20200704_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(default='abc123', max_length=6, primary_key=True, serialize=False, verbose_name='课程暗号'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses', to='account.User'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='choice_A',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='选项A'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='choice_B',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='选项B'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='choice_C',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='选项C'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='choice_D',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='选项D'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='choice_num',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='选项个数'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='correct_ans',
            field=models.SmallIntegerField(choices=[(0, 'null'), (1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')], default=0, verbose_name='正确选项'),
        ),
        migrations.AlterField(
            model_name='ppt',
            name='file',
            field=models.FileField(blank=True, default='/ppts/no_ppt.ppt', null=True, upload_to='ppts', verbose_name='课件文件'),
        ),
    ]
