# Generated by Django 3.0.8 on 2020-07-04 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200704_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discuss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', verbose_name='讨论内容')),
                ('pub_time', models.DateTimeField(auto_now=True, verbose_name='发表时间')),
                ('belong_to_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_related_diuss', to='api.Course', verbose_name='所属课程')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='', verbose_name='跟帖内容')),
                ('pub_time', models.DateTimeField(auto_now=True, verbose_name='发表时间')),
                ('belong_to_discuss', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_after_discuss', to='api.Discuss', verbose_name='跟帖')),
            ],
        ),
    ]
