# Generated by Django 3.0.8 on 2020-07-05 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_comment_discuss'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['-pub_time']},
        ),
        migrations.AlterModelOptions(
            name='ppt',
            options={'ordering': ['-pub_time']},
        ),
    ]
