# Generated by Django 3.0.8 on 2020-07-05 03:21

from django.db import migrations, models
import system.storage


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200705_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppt',
            name='file',
            field=models.FileField(blank=True, default='/ppts/no_ppt.ppt', null=True, storage=system.storage.PPTStorage(), upload_to='ppts', verbose_name='课件文件'),
        ),
    ]
