# Generated by Django 3.0.8 on 2020-07-06 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200705_1053'),
        ('api', '0008_auto_20200705_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_pubish_comment', to='account.User', verbose_name='发表用户'),
        ),
        migrations.AddField(
            model_name='comment',
            name='star_num',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='discuss',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='讨论主题'),
        ),
        migrations.AlterField(
            model_name='discuss',
            name='belong_to_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_related_discuss', to='api.Course', verbose_name='所属课程'),
        ),
    ]
