# Generated by Django 3.0.8 on 2020-07-07 01:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200706_1506'),
        ('api', '0010_auto_20200706_1506'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'ordering': ['-create_time'],
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='exercises',
            field=models.ManyToManyField(blank=True, related_name='courses', to='api.Exercise', verbose_name='课堂练习'),
        ),
        migrations.AlterField(
            model_name='course',
            name='ppts',
            field=models.ManyToManyField(blank=True, related_name='courses', to='api.PPT', verbose_name='课堂课件'),
        ),
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='courses', to='account.User', verbose_name='课堂学生'),
        ),
        migrations.CreateModel(
            name='ClassroomStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='加入时间')),
                ('out_time', models.DateTimeField(blank=True, null=True, verbose_name='退出时间')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Classroom', verbose_name='课堂')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User', verbose_name='学生')),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='belong_to_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='api.Course', verbose_name='所属课程'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='exercises',
            field=models.ManyToManyField(related_name='exercises_push_to', to='api.Exercise', verbose_name='推送的习题'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='pushed_ppt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classrooms_push_to', to='api.PPT', verbose_name='推送的课件'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='students_have_classrooms', through='api.ClassroomStudent', to='account.User', verbose_name='上课学生'),
        ),
    ]
