# Generated by Django 3.0.8 on 2020-07-07 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200707_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='exercises',
            field=models.ManyToManyField(blank=True, null=True, related_name='exercises_push_to', to='api.Exercise', verbose_name='推送的习题'),
        ),
    ]
