# Generated by Django 3.0.8 on 2020-07-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200707_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='now_class',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
