# Generated by Django 3.0.8 on 2020-07-08 01:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_course_now_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='classroomstudent',
            name='in_time',
            field=models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='加入时间'),
        ),
    ]
