# Generated by Django 3.0.8 on 2020-07-08 02:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200708_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='结束时间'),
        ),
    ]
