# Generated by Django 3.0.8 on 2020-07-08 06:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200708_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='create_time',
            field=models.DateTimeField(blank=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='end_time',
            field=models.DateTimeField(blank=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='classroomstudent',
            name='in_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.localtime, verbose_name='加入时间'),
        ),
        migrations.AlterField(
            model_name='classroomstudent',
            name='out_time',
            field=models.DateTimeField(blank=True, verbose_name='退出时间'),
        ),
    ]
